# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'textureUITest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for textureUITest
	#Reactive prgramming
    pod 'RxSwift', '6.2.0'
  	pod 'RxCocoa', '6.2.0'
  	pod 'RxGesture'
    
    # UI
    pod 'Texture'

  target 'textureUITestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'textureUITestUITests' do
    # Pods for testing
  end

end
